//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OT_Fresher.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OT_Fresher.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm dữ liệu thất bại.
        /// </summary>
        public static string addDataFail {
            get {
                return ResourceManager.GetString("addDataFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm dữ liệu thành công!.
        /// </summary>
        public static string addDataSuccess {
            get {
                return ResourceManager.GetString("addDataSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa dữ liệu thất bại!.
        /// </summary>
        public static string deleteDataFail {
            get {
                return ResourceManager.GetString("deleteDataFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa dữ liệu thành công!.
        /// </summary>
        public static string deleteDataSuccess {
            get {
                return ResourceManager.GetString("deleteDataSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật dữ liệu thất bại!.
        /// </summary>
        public static string editDataFail {
            get {
                return ResourceManager.GetString("editDataFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật dữ liệu thành công!.
        /// </summary>
        public static string editDataSuccess {
            get {
                return ResourceManager.GetString("editDataSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống đang có vấn đề, vui lòng liên hệ Dương để được trợ giúp :)) !.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh_sach_nhan_vien.xlsx.
        /// </summary>
        public static string excel_save {
            get {
                return ResourceManager.GetString("excel_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.
        /// </summary>
        public static string excel_source {
            get {
                return ResourceManager.GetString("excel_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy dữ liệu thành công!.
        /// </summary>
        public static string getDataSuccess {
            get {
                return ResourceManager.GetString("getDataSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu trên hệ thống!.
        /// </summary>
        public static string noReturnData {
            get {
                return ResourceManager.GetString("noReturnData", resourceCulture);
            }
        }
    }
}
